//
//  UIImage+FlagKit.swift
//  FlagKit
//
//  Created by Simon Blommegård on 22/09/15.
//  Copyright © 2015 Bowtie. All rights reserved.
//

import Foundation

public class FlagKit {

    public class var assetBundle: NSBundle {
        return NSBundle(forClass: FlagKit.self)
    }
}

extension FlagKit {
    
    public static func allNames() -> [String] {
        return [
            "Andorra",
            "United Arab Emirates",
            "Afghanistan",
            "Antigua & Barbuda",
            "Anguilla",
            "Albania",
            "Armenia",
            "Angola",
            "Argentina",
            "Austria",
            "Australia",
            "Åland Islands",
            "Azerbaijan",
            "Bosnia & Herzegovina",
            "Barbados",
            "Bangladesh",
            "Belgium",
            "Burkina Faso",
            "Bulgaria",
            "Bahrain",
            "Burundi",
            "Benin",
            "Bermuda",
            "Brunei",
            "Bolivia",
            "Brazil",
            "Bahamas",
            "Bhutan",
            "Botswana",
            "Belarus",
            "Belize",
            "Canada",
            "Congo - Kinshasa",
            "Central African Republic",
            "Congo - Brazzaville",
            "Switzerland",
            "Switzerland",
            "Côte d’Ivoire",
            "Chile",
            "Cameroon",
            "China",
            "Colombia",
            "Costa Rica",
            "Cuba",
            "Cape Verde",
            "Cyprus",
            "Czech Republic",
            "Germany",
            "Djibouti",
            "Denmark",
            "Dominica",
            "Dominican Republic",
            "Algeria",
            "Ecuador",
            "Estonia",
            "Egypt",
            "Eritrea",
            "Spain",
            "Ethiopia",
            "Finland",
            "Fiji",
            "Micronesia",
            "France",
            "Gabon",
            "United Kingdom",
            "Grenada",
            "Georgia",
            "Ghana",
            "Gambia",
            "Guinea",
            "Equatorial Guinea",
            "Greece",
            "Guatemala",
            "Guinea-Bissau",
            "Guyana",
            "Hong Kong SAR China",
            "Honduras",
            "Croatia",
            "Haiti",
            "Hungary",
            "Indonesia",
            "Ireland",
            "Israel",
            "India",
            "Iraq",
            "Iran",
            "Iceland",
            "Italy",
            "Jamaica",
            "Jordan",
            "Japan",
            "Kenya",
            "Kyrgyzstan",
            "Cambodia",
            "Comoros",
            "St. Kitts & Nevis",
            "North Korea",
            "South Korea",
            "Kuwait",
            "Cayman Islands",
            "Kazakhstan",
            "Laos",
            "Lebanon",
            "St. Lucia",
            "Liechtenstein",
            "Sri Lanka",
            "Liberia",
            "Lesotho",
            "Lithuania",
            "Luxembourg",
            "Latvia",
            "Libya",
            "Morocco",
            "Monaco",
            "Moldova",
            "Montenegro",
            "Madagascar",
            "Macedonia",
            "Mali",
            "Myanmar (Burma)",
            "Mongolia",
            "Macau SAR China",
            "Mauritania",
            "Montserrat",
            "Malta",
            "Mauritius",
            "Maldives",
            "Malawi",
            "Mexico",
            "Malaysia",
            "Mozambique",
            "Namibia",
            "Niger",
            "Nigeria",
            "Nicaragua",
            "Netherlands",
            "Norway",
            "Nepal",
            "New Zealand",
            "Oman",
            "Panama",
            "Peru",
            "Papua New Guinea",
            "Philippines",
            "Pakistan",
            "Poland",
            "Puerto Rico",
            "Portugal",
            "Palau",
            "Paraguay",
            "Qatar",
            "Romania",
            "Serbia",
            "Russia",
            "Rwanda",
            "Saudi Arabia",
            "Solomon Islands",
            "Seychelles",
            "Sudan",
            "Sweden",
            "Singapore",
            "Slovenia",
            "Slovakia",
            "Sierra Leone",
            "San Marino",
            "Senegal",
            "Somalia",
            "Suriname",
            "São Tomé & Príncipe",
            "El Salvador",
            "Syria",
            "Swaziland",
            "Turks & Caicos Islands",
            "Chad",
            "Togo",
            "Thailand",
            "Tajikistan",
            "Timor-Leste",
            "Turkmenistan",
            "Tunisia",
            "Tonga",
            "Turkey",
            "Trinidad & Tobago",
            "Taiwan",
            "Tanzania",
            "Ukraine",
            "Uganda",
            "United States",
            "Uruguay",
            "Uzbekistan",
            "St. Vincent & Grenadines",
            "Venezuela",
            "British Virgin Islands",
            "Vietnam",
            "Samoa",
            "Yemen",
            "South Africa",
            "Zimbabwe",
        ]
    }
    
    public static func allSpecialNames() -> [String] {
        return [
            "World",
            "European Union",
            "North America",
            "South America",
            "Europe",
            "Africa",
            "Asia",
            "Oceania",
        ]
    }
}
